version: '3'
services:
  worker:
    container_name: x721-worker
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - '8887:7777'
    volumes:
      - ../logs/x721-worker:/usr/src/app/x721-worker/logs
    env_file:
      - .env
    logging:
      driver: "json-file"
      options:
        max-size: 300m
        tag: "{{.ImageName}}|{{.Name}}|{{.ImageFullID}}|{{.FullID}}"
