enum EErrorCode {
  LOGIN_ERROR = 'LOGIN_ERROR',
  NOT_FOUND = 'NOT_FOUND',
  OTHER_ERROR = 'OTHER_ERROR',
  PARAMETERS_ERROR = 'PARAMETERS_ERROR',
  USER_NOT_ACTIVE = 'USER_NOT_ACTIVE',
  REGISTER_ERROR = 'REGISTER_ERROR',
  METADATA_ERROR = 'METADATA_ERROR',
  NOTFOUND_ERROR = 'NOTFOUND_ERROR',
}

export { EErrorCode };
