enum SYNCDATASTATUS {
  ERC1155 = 'ERC1155',
  ERC721 = 'ERC721',
  ORDER = 'ORDER',
  TRANSFER = 'TRANSFER',
}

enum ORDERTRANSFER {
  TRANSFER = 'TRANSFER',
  TRANSFERFILLED = 'TRANSFERFILLED',
}

export { SYNCDATASTATUS, ORDERTRANSFER };
